### ISSUE TITLE
Error while running the command  "rpi-source" in terminal

### ISSUE THREAD

**Issue by chinmaydashp** [RPi-Distro/rpi-source#14]
```
In file included from ./arch/arm64/include/asm/lse.h:5,
                 from ./arch/arm64/include/asm/cmpxchg.h:14,
                 from ./arch/arm64/include/asm/atomic.h:16,
                 from ./include/linux/atomic.h:7,
                 from ./include/asm-generic/bitops/atomic.h:5,
                 from ./arch/arm64/include/asm/bitops.h:25,
                 from ./include/linux/bitops.h:68,
                 from ./include/linux/log2.h:12,
                 from kernel/bounds.c:13:
./arch/arm64/include/asm/atomic_ll_sc.h: In function '__ll_sc__cmpxchg_double':
./arch/arm64/include/asm/atomic_ll_sc.h:318:38: error: '__uint128_t' undeclared (first use in this function); did you mean '__int128__'?
  318 |  : "=&r" (tmp), "=&r" (ret), "+Q" (*(__uint128_t *)ptr)  \
      |                                      ^~~~~~~~~~~
./arch/arm64/include/asm/atomic_ll_sc.h:325:1: note: in expansion of macro '__CMPXCHG_DBL'
  325 | __CMPXCHG_DBL(   ,        ,  ,         )
      | ^~~~~~~~~~~~~
./arch/arm64/include/asm/atomic_ll_sc.h:318:38: note: each undeclared identifier is reported only once for each function it appears in
  318 |  : "=&r" (tmp), "=&r" (ret), "+Q" (*(__uint128_t *)ptr)  \
      |                                      ^~~~~~~~~~~
./arch/arm64/include/asm/atomic_ll_sc.h:325:1: note: in expansion of macro '__CMPXCHG_DBL'
  325 | __CMPXCHG_DBL(   ,        ,  ,         )
      | ^~~~~~~~~~~~~
./arch/arm64/include/asm/atomic_ll_sc.h:318:51: error: expected expression before ')' token
  318 |  : "=&r" (tmp), "=&r" (ret), "+Q" (*(__uint128_t *)ptr)  \
      |                                                   ^
./arch/arm64/include/asm/atomic_ll_sc.h:325:1: note: in expansion of macro '__CMPXCHG_DBL'
  325 | __CMPXCHG_DBL(   ,        ,  ,         )
      | ^~~~~~~~~~~~~
./arch/arm64/include/asm/atomic_ll_sc.h: In function '__ll_sc__cmpxchg_double_mb':
./arch/arm64/include/asm/atomic_ll_sc.h:318:38: error: '__uint128_t' undeclared (first use in this function); did you mean '__int128__'?
  318 |  : "=&r" (tmp), "=&r" (ret), "+Q" (*(__uint128_t *)ptr)  \
      |                                      ^~~~~~~~~~~
./arch/arm64/include/asm/atomic_ll_sc.h:326:1: note: in expansion of macro '__CMPXCHG_DBL'
  326 | __CMPXCHG_DBL(_mb, dmb ish, l, "memory")
      | ^~~~~~~~~~~~~
./arch/arm64/include/asm/atomic_ll_sc.h:318:51: error: expected expression before ')' token
  318 |  : "=&r" (tmp), "=&r" (ret), "+Q" (*(__uint128_t *)ptr)  \
      |                                                   ^
./arch/arm64/include/asm/atomic_ll_sc.h:326:1: note: in expansion of macro '__CMPXCHG_DBL'
  326 | __CMPXCHG_DBL(_mb, dmb ish, l, "memory")
      | ^~~~~~~~~~~~~
make[1]: *** [scripts/Makefile.build:118: kernel/bounds.s] Error 1
make: *** [Makefile:1289: prepare0] Error 2
Traceback (most recent call last):
  File "/usr/local/bin/rpi-source", line 421, in <module>
    sh("cd %s && make modules_prepare %s" % (linux_symlink, (" > /dev/null" if args.quiet else "")))
  File "/usr/local/bin/rpi-source", line 93, in sh
    subprocess.check_call(cmd, shell=True)
  File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'cd /home/pi/linux && make modules_prepare ' returned non-zero exit status 2
```

**Comment by pelwell** [comment]
1. Say what you did.
2. Say what system you did it on.

**Comment by chinmaydashp** [comment]
I am following the setup for a flow sensor on Raspberry Pi 4B linked [here](https://developer.sensirion.com/archive/tutorials/raspberry-pi-tutorial-using-flow-sensors/). I followed the steps given in this repo and am getting the error when I run the ```rpi-source``` command in the terminal. It installs the kernel but while adding the files it is giving me this error.

**Comment by pelwell** [comment]
That's not enough information for 2 - what does `uname -a` report?

**Comment by pelwell** [comment]
After some experimentation I'm going to guess that you're on 32-bit Raspberry Pi OS with the current apt kernel and firmware. This equates to:
```
Linux raspberrypi 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64 GNU/Linux
```
i.e. a 64-bit kernel on a 32-bit userspace.
It should be possible to compile kernel modules with this configuration, but it requires a cross compiler to be installed and used by rpi-source.

Try this:
```
$ sudo apt install gcc-aarch64-linux-gnu
$ export CROSS_COMPILE=
$ rpi-source
```
Note that you may need to delete the `linux-<hash>` directory in order to get rpi-source to do anything,

You should find that rpi-source now runs to completion, just leaving you with the problem that the out-of-tree drivers are a bit old/broken. Apply the following patches to get them building:
```diff
index 87b59ca..c64048d 100644
--- a/crc8.c
+++ b/crc8.c
@@ -71,7 +71,7 @@ EXPORT_SYMBOL(crc8_populate_lsb);
  * nbytes: number of bytes in data buffer.
  * crc:        previous returned crc8 value.
  */
-u8 crc8(const u8 table[CRC8_TABLE_SIZE], u8 *pdata, size_t nbytes, u8 crc)
+u8 crc8(const u8 table[CRC8_TABLE_SIZE], const u8 *pdata, size_t nbytes, u8 crc)
 {
        /* loop over the buffer data */
        while (nbytes-- > 0)
```
```diff
diff --git a/sfxx.c b/sfxx.c
index 48e770e..38bfd65 100644
--- a/sfxx.c
+++ b/sfxx.c
@@ -433,14 +433,13 @@ fail_remove_sysfs:
        return ret;
 }
 
-static int __exit sfxx_remove(struct i2c_client *client)
+static void __exit sfxx_remove(struct i2c_client *client)
 {
        struct sfxx_data *data = i2c_get_clientdata(client);
        if (data != NULL) {
                input_unregister_device(data->dev);
                sysfs_remove_group(&client->dev.kobj, &sfxx_attr_group);
        }
-       return 0;
 }
 
 /* device ID table */
```

**Comment by pelwell** [comment]
Sorry - I paused writing my instructions to check the compiler string then didn't complete it. I should have said:
```
export CROSS_COMPILE=aarch64-linux-gnu-
```

**Comment by chinmaydashp** [comment]
Thanks a lot for your support, rpi-source compiled after adding the patch. However, the modules are not compatible with the kernel version I am currently running. I am adding the command and error message load the modules and instantiate the driver for your reference:
```
pi@raspberrypi:~/drivers $ sudo insmod crc8/crc8.ko
insmod: ERROR: could not insert module crc8/crc8.ko: Invalid module format

pi@raspberrypi:~/drivers $ sudo insmod sfxx/sfxx.ko
insmod: ERROR: could not insert module sfxx/sfxx.ko: Invalid module format

```
I tried to Install the kernel headers for current kernel version (which is same as the one you had mentioned in your comment, ```6.1.21-v8+```. However, I got the following error:
```
$ sudo apt install linux-headers-$(uname -r)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package linux-headers-6.1.21-v8
E: Couldn't find any package by glob 'linux-headers-6.1.21-v8'
```
It seems that the package for the Linux headers for this kernel version is not available in the repository. In the ```/usr/src``` folder, I am not getting the kernel headers for this version.
```
pi@raspberrypi:/usr/src $ ls
linux-headers-6.1.21+     linux-headers-6.1.21-v7l+
linux-headers-6.1.21-v7+  sense-hat
```
Is there any way around this to get the driver working?

**Comment by anakin4747** [comment]
I ran into the same errors, to finally solve it i ended up changing the OS to a headless 64bit instead of a headless 32bit RPi OS. When I did that I didn't need to run rpi-source as the build folder came included when I ran "sudo apt install raspberrypi-kernel-headers". 

@chinmaydashp,  I hope this helps your "Invalid module format" problem!
