### ISSUE TITLE
Text encoding breaks rpi-source

### ISSUE THREAD

**Issue by melissaboiko** [RPi-Distro/rpi-source#20]
I'm getting this on a freshly installed script per README:

```
 *** Linux source commit: df4d584e66a660195422ca2b7ce1d68d1181f2a2
Traceback (most recent call last):
  File "/usr/local/bin/rpi-source", line 366, in <module>
    check_diskspace(args.dest)
  File "/usr/local/bin/rpi-source", line 178, in check_diskspace
    df = sh_out("df %s" % dir)
         ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/bin/rpi-source", line 101, in sh_out
    return out.decode('ascii')
           ^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 20: ordinal not in range(128)
```

If I experimentally change the line from 'ascii' to 'utf-8' it works, so it's probably a matter of properly setting up the console to the current running locale.

**Comment by pelwell** [comment]
Out of interest, what might the value of `dir` have been?

**Comment by pelwell** [comment]
Since UTF-8 is backwards compatible with ASCII for values 0-127, I can't think of a reason not to change all occurrences of `ascii` to `utf-8`. What do you think, @popcornmix?

**Comment by popcornmix** [comment]
I believe `utf-8` is the default for strings with python 3, so yes, I don't think we should use `ascii` without a good reason.

**Comment by pelwell** [comment]
Fixed by https://github.com/RPi-Distro/rpi-source/pull/21.
